import {mkdir,writeFile} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {buildBar} from '../scene-builder.mjs';
import {exportSceneToGlb,validateGlb} from '../../cave-dinner-demo/scripts/export-glb.mjs';
const directory=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const{root,metadata}=await buildBar();
const{glb,manifest}=await exportSceneToGlb(root,metadata,{assetRoot:directory});
validateGlb(glb);
await mkdir(resolve(directory,'models'),{recursive:true});
await writeFile(resolve(directory,'models/magpie-bar.glb'),glb);
await writeFile(resolve(directory,'models/scene-manifest.json'),JSON.stringify(manifest,null,2)+'\n');
console.log(JSON.stringify({bytes:glb.length,...manifest.statistics,warnings:manifest.warnings},null,2));
